version: '2'

services:

  jenkins-agent:
    container_name: jenkins-agent
    image: vfarcic/jenkins-swarm-agent
    environment:
      #- JENKINS_URL=
      #- JENKINS_USERNAME=
      #- JENKINS_USERNAME_FILE=
      #- JENKINS_USERNAME_PASSWORD=
      #- JENKINS_USERNAME_PASSWORD_FILE=
      #- SWARM_CLIENT_OPTS=-labels swarm-executor
      - JAVA_TOOL_OPTIONS='-Xmx64m -XX:+HeapDumpOnOutOfMemoryError'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /workspace:/workspace
    restart: always
